In [1]:
import numpy as np

In [ ]:
# 1-d Array
a = np.array([1,2,3])
print(a)


[1 2 3]


In [ ]:
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(a.ndim)

1


In [ ]:
# 2-d Array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.ndim)

2


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [ ]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b=np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 0-d Array
Arr=np.array(42)
print(Arr)

42


In [ ]:
# Accessing Array Elements
arr1=np.array([1,2,3,4,5])
print(arr1[0])

1


In [ ]:
arr1[3]

np.int64(4)

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#2nd elements on 1st row
arr2[0,1]

np.int64(2)

In [ ]:
arr2[1]

array([4, 5, 6])

In [ ]:
arr2[1,1]

np.int64(5)

In [ ]:
arr3=np.array([1,2,3,4,5,6,7])
print(arr3[1:5])

[2 3 4 5]


In [ ]:
#return every other elements from index 1 to index 5.
print(arr3[1:5:2])

[2 4]


In [ ]:
#Shape of an array: shape that returns a tuple with each index having the number of corresponding.
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
#Reshape From 1-D to 2-d.
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Reshape from 1-D to 3-D.
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#iterating arrays
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [ ]:
# iterating on the elements of the following 2-D array:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [ ]:
# Numpy joining array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# splitting numpy arrays
# Splitting in reverse operation of joining
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# random numbers
#numpy offers the rendom module to work with random numbers
#generate a random integer from 0 to 100
from numpy import random
x=random.randint(100)
x

62

In [ ]:
 # Random module's rand() method reurns a random float between 0 to 1
 x= random.rand()
 print(x)

0.30172068220489623


In [ ]:
# generate random array
x=random.randint(100, size=(5))
print(x)

[47 22 36 53 51]


In [ ]:
# A 2-D array with 3 rows , each row containg 5 random integrs from 0 to 100
x=random.randint(100,size=(3,5))
print(x)

[[12 48 54 90 56]
 [97 99 70 13 47]
 [79 99 94 18 99]]


In [ ]:
# generate a 1-D array containing 5 random floats
x=random.rand(5)
print(x)

[0.87912144 0.88465475 0.2262473  0.26523975 0.21674173]


In [ ]:
x=random.rand(3,5)
print(x)

[[0.76149063 0.53329409 0.43658487 0.41528369 0.98382705]
 [0.8323261  0.10540465 0.20786371 0.13522798 0.3013129 ]
 [0.11145456 0.14795442 0.09158064 0.8324928  0.93292417]]


In [ ]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np

In [ ]:
# defining a list of different car companies or string elements
arr_str=['mercedes','bmw','audi','volvo','suzuki']

#defining a list of number of cylinders in car or numerical elements
arr_num=[1800,1400,1600,1000,1200]

In [ ]:
np_arr_str=np.array(arr_str)

# converting the list into numpy

np_arr_num=np.array(arr_num)

In [ ]:
print('Numpy Array (arr_str): ',np_arr_str)
print('Numpy Array (arr_num): ',np_arr_num)

Numpy Array (arr_str):  ['mercedes' 'bmw' 'audi' 'volvo' 'suzuki']
Numpy Array (arr_num):  [1800 1400 1600 1000 1200]


In [ ]:
# printing the data type of lists
print('Numpy Array (arr_str): ',type(np_arr_str))
print('Numpy Array (arr_num): ',type(np_arr_num))

Numpy Array (arr_str):  <class 'numpy.ndarray'>
Numpy Array (arr_num):  <class 'numpy.ndarray'>


In [ ]:
print('Numpy Array (arr_str): ',type(arr_str))
print('Numpy Array (arr_num): ',type(arr_num))

Numpy Array (arr_str):  <class 'list'>
Numpy Array (arr_num):  <class 'list'>


Numpy matrix
A matrix is a two-Dimensional data structuure where elements are arranged into two columns

In [ ]:
arr2=np.arange(start=0,stop=10)
print(arr2)



arr2=np.arange(0,10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [2]:
matrix2= np.linspace(0,5)
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [3]:
matrix6=np.eye(5)
matrix6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
print('sine Function',np.sin(4))
print('cosine Function', np.cos(4))
print('tangent Function', np.tan(4))

sine Function -0.7568024953079282
cosine Function -0.6536436208636119
tangent Function 1.1578212823495775


In [5]:
# exponents function

In [6]:
np.exp(2)

np.float64(7.38905609893065)

In [8]:
arr5=np.array([1,2,3,4,5])
np.exp(arr5)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [9]:
#Logarithms

In [10]:
#by default numpy takes the base log as e
np.log(2)

np.float64(0.6931471805599453)

In [11]:
np.log(arr5)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [12]:
np.log10(10)

np.float64(1.0)

In [13]:
# arithmetic on lists

In [14]:
l1=[1,2,3,4]
l2=[4,5,6]
print(l1+l2)

[1, 2, 3, 4, 4, 5, 6]


In [23]:
# we can +-*/ arrays together
# defining two arrays
arr7=np.arange(1,6)
print('arr7',arr7)

arr8=np.arange(3,8)
print('arr8',arr8)

arr7 [1 2 3 4 5]
arr8 [3 4 5 6 7]


In [24]:
print('addition: ',arr7+arr8)
print('subtraction: ',arr7-arr8)
print('multiplication:',arr7*arr8)
print('division:',arr7/arr8)
print('inverse:',1/arr7)
print('powers:',arr7**arr8)

addition:  [ 4  6  8 10 12]
subtraction:  [-2 -2 -2 -2 -2]
multiplication: [ 3  8 15 24 35]
division: [0.33333333 0.5        0.6        0.66666667 0.71428571]
inverse: [1.         0.5        0.33333333 0.25       0.2       ]
powers: [    1    16   243  4096 78125]


In [28]:
matrix7=np.arange(1,10).reshape(3,3)
print(matrix7)
matrix8=np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
print('addition: /n',matrix7+matrix8)
print('subtraction: /n',matrix7-matrix8)
print('multiplication: /n',matrix7*matrix8)
print('division: /n',matrix7/matrix8)

addition: /n [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
subtraction: /n [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
multiplication: /n [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
division: /n [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


/tmp/ipython-input-2006186751.py:4: RuntimeWarning: divide by zero encountered in divide
  print('division: /n',matrix7/matrix8)


Linear algebra matrix multiplications

In [31]:
matrix9=np.arange(1,10).reshape(3,3)
print('first matrix: /n', matrix9)

matrix10=np.arange(1,10).reshape(3,3)
print('second matrix: /n', matrix10)
print('')
print('matrix multiplication: /n',np.dot(matrix9,matrix10))

first matrix: /n [[1 2 3]
 [4 5 6]
 [7 8 9]]
second matrix: /n [[1 2 3]
 [4 5 6]
 [7 8 9]]

matrix multiplication: /n [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [33]:
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
np.transpose(matrix9)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
matrix9.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
#genrating random values in matrix
rand_matrix=np.random.randn(1,5,10)
rand_matrix

array([[[ 0.44402445, -0.9791358 ,  1.1842072 , -1.27050658,
         -1.15960426,  0.71669137,  0.28598449,  0.71434456,
          0.8266824 ,  0.03794179],
        [-1.18502238, -0.12008256,  1.00935829,  1.70266427,
          0.60991769, -0.28069574, -0.38156886, -1.36317088,
         -0.06866588, -0.12528745],
        [-0.72878382, -0.08688986,  1.33114818,  0.35644732,
          0.3860612 , -0.67877898, -1.3428253 ,  0.73077622,
          0.39179832,  0.43104618],
        [-1.19423381, -1.40765665, -1.0289451 , -0.09223404,
         -1.12710149, -0.31895428, -0.14756964, -1.30486012,
         -0.29586723, -0.12544697],
        [-0.6961543 ,  0.90973723, -0.39807361, -0.8279147 ,
          1.16994643,  0.86080207,  0.79191679,  0.14785577,
          0.13832861, -1.55064722]]])